# This is a basic workflow to help you get started with Actions

name: VersionUpdater

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ development ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version:
        - 'pypy-3.7' # the latest available version of PyPy that supports Python 3.7
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        fetch-depth: 0    # Fetch all commit and tag history from branches
        
    - run: |
          pip install pdfkit
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout development
          git pull origin development
      
    - name: Install wkhtmltopdf
      run: |
          sudo apt install wkhtmltopdf
          sudo apt install xvfb   # Used to prevent X-issues, see https://stackoverflow.com/questions/51787618/wkhtmltopdf-pdfkit-could-not-connect-to-any-x-display
    
    - name: Update version files
      run: |
          python tools/version_control.py update
          git add .
          git commit --amend --no-edit   
      
    - name: Update status-reports
      run: |
          python tools/version_control.py status-reports
          git add .
          git commit -m "Auto-generated status reports"
          
    - name: Git push
      run: |
          git push -f origin development